server:
  port: 19099

spring:
  application:
    name: rider-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false # sql 로깅
        format_sql: false # SQL 문 정렬하여 출력
        highlight_sql: false # SQL 문 색 부여
  #        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
    path: /rider-service/v3/api-docs
  swagger-ui:
    path: /rider-service/swagger-ui.html

log:
  logstash:
    host: ${LOG_STASH_HOST}
    port: ${LOG_STASH_PORT}
